#!/bin/csh -ef
#############################################################################
#                                                                           #
# Title: Generate Initial Model                                             #
#                                                                           #
# (C) 2dx.org, GNU Plublic License.                                         #
#                                                                           #
# Created..........: 05/19/2007                                             #
# Last Modification: 05/19/2007                                             #
# Author...........: 2dx.org                                                #
#                                                                           #
#############################################################################
#
# SORTORDER: 30
#
# MANUAL: Uses the volume.map file to cut the initial volume for the 3D single-particle refinment.
#
# MANUAL: The resulting map has to be centred and the only the central protein should be inside the mask.
#
# DISPLAY: particle_size_sp2dx
# DISPLAY: cont_folder_sp2dx
# DISPLAY: binn_sp2dx
# DISPLAY: offsets_sp2dx
# DISPLAY: mrc_init_sp2dx
#
# DISPLAY: reconstruction_masking_sp2dx
# DISPLAY: reconstruction_masking_r_params_sp2dx
# DISPLAY: reconstruction_masking_h_params_sp2dx
# DISPLAY: reconstruction_masking_ellipse_params_sp2dx
# DISPLAY: lp_volume_filter_init_sp2dx
# DISPLAY: show_sights_sp2dx
#
#$end_local_vars
#
set bin_2dx = ""
set proc_2dx = ""
#
set particle_size_sp2dx = ""
set cont_folder_sp2dx = ""
set binn_sp2dx = ""
set offsets_sp2dx = ""
set mrc_init_sp2dx = ""
#
set reconstruction_masking_sp2dx = ""
set reconstruction_masking_r_params_sp2dx = ""
set reconstruction_masking_h_params_sp2dx = ""
set reconstruction_masking_ellipse_params_sp2dx = ""
set lp_volume_filter_init_sp2dx = ""
set show_sights_sp2dx = ""
#
#$end_vars

echo "<<@progress: 1>>"

set scriptname = GenerateInitModels

set missing_cone_sp2dx = "0"
set lp_volume_filter_incharge = $lp_volume_filter_init_sp2dx

\rm -f LOGS/${scriptname}.results
echo "<<@evaluate>>"

echo "set called now"
#rm mergevars_written_to_file.txt
set > mergevars_written_to_file.txt

${bin_2dx}/2dx_singleparticle/GenerateInitModel.exe

echo "<<@progress: 100>>"

